spring:
    main:
        banner-mode: "off"

    datasource:
        url: jdbc:h2:file:./data/h2/elibrary;DB_CLOSE_ON_EXIT=TRUE
        username: admin
        password: nimda

    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update

elibrary:
    logo: "Welcome to e-library! \n
        ...._______..................\n
        .../      /,.....Created.by..\n
        ../      //.....Panas.Sydor..\n
        ./______//...................\n
        (______(/....................\n
        ............................."
    default-book-author: Unknown